{
 "title": "VMware vSphere Monitoring",
 "tags": [
  "vsphere",
  "alloy",
  "prometheus",
  "otel"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "datacenter",
    "query": {
     "query": "label_values(vcenter_cluster_host_count{job=\"integrations/vsphere\"}, vcenter_datacenter_name)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(vcenter_cluster_cpu_limit_MHz{job=\"integrations/vsphere\", vcenter_datacenter_name=~\"$datacenter\"},vcenter_cluster_name)"
    }
   },
   {
    "name": "host",
    "query": {
     "query": "label_values(vcenter_host_cpu_usage_MHz{job=\"integrations/vsphere\", vcenter_datacenter_name=~\"$datacenter\", vcenter_cluster_name=~\"$cluster\"}, vcenter_host_name)"
    }
   },
   {
    "name": "vm",
    "query": {
     "query": "label_values(vcenter_vm_cpu_usage_MHz{job=\"integrations/vsphere\", vcenter_datacenter_name=~\"$datacenter\", vcenter_cluster_name=~\"$cluster\", vcenter_host_name=~\"$host\"}, vcenter_vm_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "vSphere Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Clusters",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (vcenter_cluster_name) (vcenter_cluster_cpu_limit_MHz{job=\"integrations/vsphere\", vcenter_datacenter_name=~\"$datacenter\", vcenter_cluster_name=~\"$cluster\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Hosts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vcenter_cluster_host_count{job=\"integrations/vsphere\", vcenter_datacenter_name=~\"$datacenter\", vcenter_cluster_name=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total VMs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vcenter_cluster_vm_count{job=\"integrations/vsphere\", vcenter_datacenter_name=~\"$datacenter\", vcenter_cluster_name=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vcenter_cluster_cpu_effective_MHz{job=\"integrations/vsphere\", vcenter_datacenter_name=~\"$datacenter\", vcenter_cluster_name=~\"$cluster\"}) / sum(vcenter_cluster_cpu_limit_MHz{job=\"integrations/vsphere\", vcenter_datacenter_name=~\"$datacenter\", vcenter_cluster_name=~\"$cluster\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vcenter_cluster_memory_effective_bytes{job=\"integrations/vsphere\", vcenter_datacenter_name=~\"$datacenter\", vcenter_cluster_name=~\"$cluster\"}) / sum(vcenter_cluster_memory_limit_bytes{job=\"integrations/vsphere\", vcenter_datacenter_name=~\"$datacenter\", vcenter_cluster_name=~\"$cluster\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "vSphere Clusters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "repeat": "cluster" },
  {
   "title": "CPU Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(vcenter_cluster_cpu_effective_MHz{job=\"integrations/vsphere\", vcenter_datacenter_name=~\"$datacenter\", vcenter_cluster_name=\"$cluster\"} / vcenter_cluster_cpu_limit_MHz{job=\"integrations/vsphere\", vcenter_datacenter_name=~\"$datacenter\", vcenter_cluster_name=\"$cluster\"}) * 100",
     "legendFormat": "{{vcenter_cluster_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(vcenter_cluster_memory_effective_bytes{job=\"integrations/vsphere\", vcenter_datacenter_name=~\"$datacenter\", vcenter_cluster_name=\"$cluster\"} / vcenter_cluster_memory_limit_bytes{job=\"integrations/vsphere\", vcenter_datacenter_name=~\"$datacenter\", vcenter_cluster_name=\"$cluster\"}) * 100",
     "legendFormat": "{{vcenter_cluster_name}}"
    }
   ]
  },
  {
   "title": "Host Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vcenter_cluster_host_count{effective=\"true\",job=\"integrations/vsphere\", vcenter_datacenter_name=~\"$datacenter\", vcenter_cluster_name=~\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VM Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vcenter_cluster_vm_count{job=\"integrations/vsphere\", vcenter_datacenter_name=~\"$datacenter\", vcenter_cluster_name=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Datastores Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "vcenter_datastore_disk_utilization_percent{job=\"integrations/vsphere\",vcenter_datacenter_name=~\"$datacenter\"}",
     "legendFormat": "{{vcenter_datastore_name}}"
    }
   ]
  },
  {
   "title": "vSphere Hosts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "repeat": "host",
   "collapsed": true,
   "panels": [
    {
     "title": "Host CPU Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 164 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "vcenter_host_cpu_utilization_percent{job=\"integrations/vsphere\", vcenter_datacenter_name=~\"$datacenter\", vcenter_cluster_name=~\"$cluster\", vcenter_host_name=~\"$host\"}",
       "legendFormat": "{{vcenter_host_name}}"
      }
     ]
    },
    {
     "title": "Host Memory Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 164 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "vcenter_host_memory_utilization_percent{job=\"integrations/vsphere\", vcenter_datacenter_name=~\"$datacenter\", vcenter_cluster_name=~\"$cluster\", vcenter_host_name=~\"$host\"}",
       "legendFormat": "{{vcenter_host_name}}"
      }
     ]
    },
    {
     "title": "Host Network Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 172 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by (vcenter_host_name, direction) (vcenter_host_network_throughput{job=\"integrations/vsphere\", vcenter_datacenter_name=~\"$datacenter\", vcenter_cluster_name=~\"$cluster\", vcenter_host_name=~\"$host\", object=\"\"}) * 1000",
       "legendFormat": "{{vcenter_host_name}} - {{direction}}"
      },
      {
       "expr": "vcenter_host_network_usage{job=\"integrations/vsphere\", vcenter_datacenter_name=~\"$datacenter\", vcenter_cluster_name=~\"$cluster\", vcenter_host_name=~\"$host\", object=\"\"} * 1000",
       "legendFormat": "{{vcenter_host_name}} - total usage"
      }
     ]
    },
    {
     "title": "Host Disk Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 172 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum by (vcenter_host_name, direction) (vcenter_host_disk_latency_avg_milliseconds{job=\"integrations/vsphere\", vcenter_datacenter_name=~\"$datacenter\", vcenter_cluster_name=~\"$cluster\", vcenter_host_name=~\"$host\"})",
       "legendFormat": "{{vcenter_host_name}} - {{direction}}"
      }
     ]
    }
   ]
  },
  {
   "title": "vSphere Virtual Machines",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "repeat": "vm",
   "collapsed": true,
   "panels": [
    {
     "title": "VM CPU / Memory / Disk Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 538 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "vcenter_vm_cpu_utilization_percent{job=\"integrations/vsphere\", vcenter_datacenter_name=~\"$datacenter\", vcenter_cluster_name=~\"$cluster\", vcenter_host_name=~\"$host\", vcenter_vm_name=~\"$vm\"}",
       "legendFormat": "% CPU: {{vcenter_vm_name}}"
      },
      {
       "expr": "vcenter_vm_memory_utilization_percent{job=\"integrations/vsphere\", vcenter_datacenter_name=~\"$datacenter\", vcenter_cluster_name=~\"$cluster\", vcenter_host_name=~\"$host\", vcenter_vm_name=~\"$vm\"}",
       "legendFormat": "% Memory: {{vcenter_vm_name}}"
      },
      {
       "expr": "vcenter_vm_disk_utilization_percent{job=\"integrations/vsphere\", vcenter_datacenter_name=~\"$datacenter\", vcenter_cluster_name=~\"$cluster\", vcenter_host_name=~\"$host\", vcenter_vm_name=~\"$vm\"}",
       "legendFormat": "% Disk: {{vcenter_vm_name}}"
      }
     ]
    },
    {
     "title": "VM Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 538 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "vcenter_vm_memory_usage_mebibytes{job=\"integrations/vsphere\", vcenter_datacenter_name=~\"$datacenter\", vcenter_cluster_name=~\"$cluster\", vcenter_host_name=~\"$host\", vcenter_vm_name=~\"$vm\"} * 1024 * 1024",
       "legendFormat": "Usage: {{vcenter_vm_name}}"
      },
      {
       "expr": "vcenter_vm_memory_ballooned_mebibytes{job=\"integrations/vsphere\", vcenter_datacenter_name=~\"$datacenter\", vcenter_cluster_name=~\"$cluster\", vcenter_host_name=~\"$host\", vcenter_vm_name=~\"$vm\"} * 1024 * 1024",
       "legendFormat": "Ballooned: {{vcenter_vm_name}}"
      },
      {
       "expr": "vcenter_vm_memory_swapped_mebibytes{job=\"integrations/vsphere\", vcenter_datacenter_name=~\"$datacenter\", vcenter_cluster_name=~\"$cluster\", vcenter_host_name=~\"$host\", vcenter_vm_name=~\"$vm\"} * 1024 * 1024",
       "legendFormat": "Swapped: {{vcenter_vm_name}}"
      }
     ]
    },
    {
     "title": "VM Network Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 546 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by(vcenter_vm_name, direction) (vcenter_vm_network_throughput_bytes_per_second{job=\"integrations/vsphere\", vcenter_datacenter_name=~\"$datacenter\", vcenter_cluster_name=~\"$cluster\", vcenter_host_name=~\"$host\", vcenter_vm_name=~\"$vm\", object=\"\"}) * 1000",
       "legendFormat": "{{vcenter_vm_name}} - {{direction}}"
      },
      {
       "expr": "sum by(vcenter_vm_name) (vcenter_vm_network_usage{job=\"integrations/vsphere\", vcenter_datacenter_name=~\"$datacenter\", vcenter_cluster_name=~\"$cluster\", vcenter_host_name=~\"$host\", vcenter_vm_name=~\"$vm\", object=\"\"}) * 1000",
       "legendFormat": "{{vcenter_vm_name}} - total usage"
      }
     ]
    },
    {
     "title": "VM Disk Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 546 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum by (vcenter_vm_name, direction) (vcenter_vm_disk_latency_avg_milliseconds{job=\"integrations/vsphere\", vcenter_datacenter_name=~\"$datacenter\", vcenter_cluster_name=~\"$cluster\", vcenter_host_name=~\"$host\", vcenter_vm_name=~\"$vm\"})",
       "legendFormat": "{{vcenter_vm_name}} - {{direction}}"
      }
     ]
    },
    {
     "title": "VM Disk Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 554 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "expr": "sum by(vcenter_vm_name, direction) (vcenter_vm_disk_throughput{job=\"integrations/vsphere\", vcenter_datacenter_name=~\"$datacenter\", vcenter_cluster_name=~\"$cluster\", vcenter_host_name=~\"$host\", vcenter_vm_name=~\"$vm\", object=\"\"})",
       "legendFormat": "{{vcenter_vm_name}} - {{direction}}"
      }
     ]
    },
    {
     "title": "VM Disk Space",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 554 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "vcenter_vm_disk_usage_bytes{job=\"integrations/vsphere\", vcenter_datacenter_name=~\"$datacenter\", vcenter_cluster_name=~\"$cluster\", vcenter_host_name=~\"$host\", vcenter_vm_name=~\"$vm\"}",
       "legendFormat": "{{vcenter_vm_name}} - {{disk_state}}"
      },
      {
       "expr": "sum by(vcenter_vm_name) (vcenter_vm_disk_usage_bytes{job=\"integrations/vsphere\", vcenter_datacenter_name=~\"$datacenter\", vcenter_cluster_name=~\"$cluster\", vcenter_host_name=~\"$host\", vcenter_vm_name=~\"$vm\"})",
       "legendFormat": "{{vcenter_vm_name}} - allocated"
      }
     ]
    }
   ]
  }
 ]
}